### ISSUE TITLE
Bug - UserDB error: email failed - when creating account

### ISSUE THREAD

**Issue by wip-abramson** [WebOfTrustInfo/prototype_vRWOT#2]
Joe and I were both unable to create an account. It returned the following error in the frontent - UserDB error: email failed. Nothing was output in the server console.

Perhaps the email server is not running?

**Comment by noahgibbs** [comment]
Unfortunately, Linodes require you to file a ticket in order to send email from them. That error won't stop you from making an account and approving it from an admin account, but it *will* display the error and need to be manually verified :-/

**Comment by noahgibbs** [comment]
So I suppose I should do that for this prototype - just realised, oh yeah, we're keeping this one for a bit. I had gotten used to rebuilding them over and over while debugging the stackscript...

**Comment by noahgibbs** [comment]
Okay. I've created a ticket. I'll let you know when I hear back.

**Comment by ChristopherA** [comment]
The key thing to understand is that until email is properly set up (which is complicated), you have to use the admin interface to override the requirement to confirm the email confirmation.

**Comment by noahgibbs** [comment]
Linode just said they have removed that restriction account-wide for the SkotOS account. So I'll revisit the email configuration on the node, with the assumption that I've misconfigured it somehow. It may be something simple, I'll doublecheck everything.

In the mean time, yes, the email admin interface should be a fix for your early admin accounts.

**Comment by noahgibbs** [comment]
I've fixed this in the Linode scripts in mainline ChatTheatre/SkotOS. I can't remember if I applied the fix manually to the RWOT server -- I'll check this and fix it soon.
